### ISSUE TITLE
How to match path params for mock response?

### ISSUE THREAD

**Issue by mikespub** [canvural/php-openapi-faker#149]
I may have missed something obvious here, but if I have an OpenAPI spec with path params like "/articles/{slug}" and I try to mock a response for a particular request with path "/articles/this-is-a-slug", this throws an exception:

Exception: OpenAPI spec does not have a path for GET /articles/this-is-a-slug

Trying the same with actual path "/articles/{slug}" works fine though.

Looking at the code in OpenAPIFaker->findOperation(), you only use SpecFinder() from League\OpenAPIValidation\PSR7 which will only match the exact same address, and not PathFinder() which would try to match path params as well - is that by design?

Thanks

**Comment by canvural** [comment]
Hi,

I don't think there is really a valid reason why `SpecFinder` is used. I guess I just didn't think of resolving paths like that.

If you are up for creating a PR that changes this I'd merge it 👍🏽

**Comment by mikespub** [comment]
Thanks for the clarification. I'm trying to implement an existing API spec using a new server stack, and this library looked like a good way to handle requests after routing and return mock responses while I'm experimenting. It wasn't too low-level to be of immediate use to me, or too extensive and tied to a particular framework.

I'm afraid I won't be able to contribute a PR on this, but keep up the good work 👍
